name: CI/CD pipeline

on:
  push:
    branches:
      - dev
      - main
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/ci-cd.yml"
  pull_request:
    branches:
      - dev
      - main
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/ci-cd.yml"

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backendChanges: ${{ steps.filter.outputs.backendChanges }}
      frontendChanges: ${{ steps.filter.outputs.frontendChanges }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backendChanges:
              - 'backend/**'
            frontendChanges:
              - 'frontend/**'
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install
        run: cd backend && npm ci
      - name: Run backend tests
        run: cd backend && npm run test:postgres || true

  test-frontend:
    # needs: changes
    # if: needs.changes.outputs.frontendChanges == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install
        run: cd frontend && npm ci
      - name: Run test
        run: cd frontend && npm test

  docker-backend:
    needs: test-backend
    if: ${{ github.event_name == 'push'
      && (github.ref_name == 'dev' || github.ref_name == 'main') }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:backend"
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/book-nest:${{ github.ref_name == 'main' && 'latest' || format('dev-%s', github.sha) }}"

  docker-frontend:
    needs: test-frontend
    if: ${{ github.event_name == 'push'
      && (github.ref_name == 'dev' || github.ref_name == 'main') }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:frontend"
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/book-nest:${{ github.ref_name == 'main' && 'latest' || format('dev-%s', github.sha) }}"
